# Generated by Django 4.2.20 on 2025-04-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='broker',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='broker',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
