# Generated by Django 4.2.20 on 2025-04-10 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowers', '0001_initial'),
        ('products', '0001_initial'),
        ('applications', '0001_initial'),
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bdm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='borrowers.borrower'),
        ),
        migrations.AddField(
            model_name='application',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='brokers.broker'),
        ),
        migrations.AddField(
            model_name='application',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='products.product'),
        ),
        migrations.AddField(
            model_name='application',
            name='qs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.qs'),
        ),
        migrations.AddField(
            model_name='application',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.referral'),
        ),
        migrations.AddField(
            model_name='application',
            name='valuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.valuer'),
        ),
    ]
