# Generated by Django 4.2.20 on 2025-04-11 03:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMetadataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('select', 'Select')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, help_text='Options for select field type', null=True)),
                ('document_types', models.JSONField(blank=True, help_text='Document types this field applies to', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_metadata_fields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='documentapproval',
            options={'ordering': ['requested_date']},
        ),
        migrations.RenameField(
            model_name='documentapproval',
            old_name='created_at',
            new_name='requested_date',
        ),
        migrations.RenameField(
            model_name='documentapproval',
            old_name='approval_date',
            new_name='response_date',
        ),
        migrations.RenameField(
            model_name='documentsignaturerequest',
            old_name='completed_date',
            new_name='response_date',
        ),
        migrations.RemoveField(
            model_name='documentapproval',
            name='approval_comments',
        ),
        migrations.RemoveField(
            model_name='documentsignature',
            name='signature_image',
        ),
        migrations.RemoveField(
            model_name='documentsignaturerequest',
            name='signature_token',
        ),
        migrations.AddField(
            model_name='document',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='auto_categorize_rules',
            field=models.JSONField(blank=True, help_text='Rules for auto-categorization', null=True),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='color',
            field=models.CharField(blank=True, help_text="Color code (e.g., '#FF5733')", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='icon',
            field=models.CharField(blank=True, help_text="Icon class name (e.g., 'fa-file-pdf')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System categories cannot be deleted'),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='verification_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentapproval',
            name='approval_level',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='documentapproval',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documentsignature',
            name='signature_type',
            field=models.CharField(blank=True, choices=[('drawn', 'Drawn Signature'), ('typed', 'Typed Signature'), ('digital', 'Digital Signature')], default='typed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documentsignaturerequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_shared', models.BooleanField(default=False, help_text='Whether this collection is shared with other users')),
                ('icon', models.CharField(blank=True, help_text="Icon class name (e.g., 'fa-folder')", max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text="Color code (e.g., '#4287f5')", max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_collections', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcollections', to='documents.documentcollection')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.documentcollection'),
        ),
        migrations.CreateModel(
            name='DocumentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('supersedes', 'Supersedes'), ('supplements', 'Supplements'), ('references', 'References'), ('requires', 'Requires'), ('amends', 'Amends'), ('custom', 'Custom')], max_length=50)),
                ('custom_type', models.CharField(blank=True, help_text='Custom relationship type name', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_relationships', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='documents.document')),
                ('target_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='documents.document')),
            ],
            options={
                'unique_together': {('source_document', 'target_document', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_metadata', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_metadata', to='documents.document')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='documents.custommetadatafield')),
            ],
            options={
                'unique_together': {('document', 'field')},
            },
        ),
    ]
