# Generated by Django 4.2.20 on 2025-04-10 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_type', models.CharField(choices=[('fixed', 'Fixed Rate'), ('variable', 'Variable Rate'), ('interest_only', 'Interest Only')], max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_term_years', models.IntegerField()),
                ('compounding_period', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_payments', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='applications.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='calculator.loancalculation')),
            ],
            options={
                'ordering': ['payment_number'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('fee_type', models.CharField(choices=[('application', 'Application Fee'), ('establishment', 'Establishment Fee'), ('ongoing', 'Ongoing Fee'), ('late_payment', 'Late Payment Fee'), ('early_repayment', 'Early Repayment Fee'), ('other', 'Other Fee')], max_length=20)),
                ('calculation_method', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Loan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='fees', to='products.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_waived', models.BooleanField(default=False)),
                ('waiver_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_fees', to='applications.application')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.fee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
