# Generated by Django 4.2.20 on 2025-04-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_interest_rate_product_is_active_and_more'),
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='calculator_fees', to='products.product'),
        ),
    ]
