# Generated by Django 4.2.20 on 2025-04-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('stage_change', 'Stage Change'), ('repayment_reminder', 'Repayment Reminder'), ('loan_maturity', 'Loan Maturity'), ('note_reminder', 'Note Reminder'), ('overdue_payment', 'Overdue Payment'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('trigger_date', models.DateTimeField()),
                ('sent_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-trigger_date'],
            },
        ),
    ]
