# Generated by Django 4.2.20 on 2025-04-14 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_loan_amount',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='min_credit_score',
            field=models.IntegerField(default=650),
        ),
        migrations.AddField(
            model_name='product',
            name='min_loan_amount',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='term_months',
            field=models.IntegerField(default=360),
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_percentage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='products.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
